// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type SearchRequest struct {
	OrderID string `form:"OrderID"`
}

type SearchResponse struct {
	OrderID  string `json:"orderID"`
	Status   int    `json:"status"`
	Username string `json:"username"`
}
