// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	user2FieldNames          = builder.RawFieldNames(&User2{})
	user2Rows                = strings.Join(user2FieldNames, ",")
	user2RowsExpectAutoSet   = strings.Join(stringx.Remove(user2FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	user2RowsWithPlaceHolder = strings.Join(stringx.Remove(user2FieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTestUser2IdPrefix       = "cache:test:user2:id:"
	cacheTestUser2UserIdPrefix   = "cache:test:user2:userId:"
	cacheTestUser2UsernamePrefix = "cache:test:user2:username:"
)

type (
	user2Model interface {
		Insert(ctx context.Context, data *User2) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User2, error)
		FindOneByUserId(ctx context.Context, userId int64) (*User2, error)
		FindOneByUsername(ctx context.Context, username string) (*User2, error)
		Update(ctx context.Context, data *User2) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUser2Model struct {
		sqlc.CachedConn
		table string
	}

	User2 struct {
		Id         int64          `db:"id"`
		UserId     int64          `db:"user_id"`
		Username   string         `db:"username"`
		Password   string         `db:"password"`
		Email      sql.NullString `db:"email"`
		Gender     int64          `db:"gender"`
		CreateTime time.Time      `db:"create_time"`
		UpdateTime time.Time      `db:"update_time"`
	}
)

func newUser2Model(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUser2Model {
	return &defaultUser2Model{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user2`",
	}
}

func (m *defaultUser2Model) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	testUser2IdKey := fmt.Sprintf("%s%v", cacheTestUser2IdPrefix, id)
	testUser2UserIdKey := fmt.Sprintf("%s%v", cacheTestUser2UserIdPrefix, data.UserId)
	testUser2UsernameKey := fmt.Sprintf("%s%v", cacheTestUser2UsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, testUser2IdKey, testUser2UserIdKey, testUser2UsernameKey)
	return err
}

func (m *defaultUser2Model) FindOne(ctx context.Context, id int64) (*User2, error) {
	testUser2IdKey := fmt.Sprintf("%s%v", cacheTestUser2IdPrefix, id)
	var resp User2
	err := m.QueryRowCtx(ctx, &resp, testUser2IdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", user2Rows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUser2Model) FindOneByUserId(ctx context.Context, userId int64) (*User2, error) {
	testUser2UserIdKey := fmt.Sprintf("%s%v", cacheTestUser2UserIdPrefix, userId)
	var resp User2
	err := m.QueryRowIndexCtx(ctx, &resp, testUser2UserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", user2Rows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUser2Model) FindOneByUsername(ctx context.Context, username string) (*User2, error) {
	testUser2UsernameKey := fmt.Sprintf("%s%v", cacheTestUser2UsernamePrefix, username)
	var resp User2
	err := m.QueryRowIndexCtx(ctx, &resp, testUser2UsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", user2Rows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, username); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUser2Model) Insert(ctx context.Context, data *User2) (sql.Result, error) {
	testUser2IdKey := fmt.Sprintf("%s%v", cacheTestUser2IdPrefix, data.Id)
	testUser2UserIdKey := fmt.Sprintf("%s%v", cacheTestUser2UserIdPrefix, data.UserId)
	testUser2UsernameKey := fmt.Sprintf("%s%v", cacheTestUser2UsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, user2RowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Username, data.Password, data.Email, data.Gender)
	}, testUser2IdKey, testUser2UserIdKey, testUser2UsernameKey)
	return ret, err
}

func (m *defaultUser2Model) Update(ctx context.Context, newData *User2) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	testUser2IdKey := fmt.Sprintf("%s%v", cacheTestUser2IdPrefix, data.Id)
	testUser2UserIdKey := fmt.Sprintf("%s%v", cacheTestUser2UserIdPrefix, data.UserId)
	testUser2UsernameKey := fmt.Sprintf("%s%v", cacheTestUser2UsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, user2RowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Username, newData.Password, newData.Email, newData.Gender, newData.Id)
	}, testUser2IdKey, testUser2UserIdKey, testUser2UsernameKey)
	return err
}

func (m *defaultUser2Model) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTestUser2IdPrefix, primary)
}

func (m *defaultUser2Model) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", user2Rows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUser2Model) tableName() string {
	return m.table
}
