// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type ShowRequest struct {
	ShortUrl string `shortUrl validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}
